//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.01 at 03:42:28 PM SGT 
//


package com.emc.sett.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CnmeaSettReT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CnmeaSettReT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adjustments" type="{http://www.model.sett.emc.com}AdjustmentT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="opGstGmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="opGstLmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="opGstLmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="opGstNmea" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="accountId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="gmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="periodId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="lmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="nmea" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="settId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ipGstGmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nmeaRequired" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CnmeaSettReT", propOrder = {
    "adjustments",
    "opGstGmef",
    "opGstLmee",
    "opGstLmef",
    "opGstNmea",
    "accountId",
    "gmee",
    "gmef",
    "periodId",
    "lmee",
    "lmef",
    "nmea",
    "settId",
    "ipGstGmee",
    "version",
    "nmeaRequired"
})
public class CnmeaSettReT {

    protected List<AdjustmentT> adjustments;
    @XmlElement(required = true)
    protected BigDecimal opGstGmef;
    @XmlElement(required = true)
    protected BigDecimal opGstLmee;
    @XmlElement(required = true)
    protected BigDecimal opGstLmef;
    @XmlElement(required = true)
    protected BigDecimal opGstNmea;
    @XmlElement(required = true)
    protected String accountId;
    @XmlElement(required = true)
    protected BigDecimal gmee;
    @XmlElement(required = true)
    protected BigDecimal gmef;
    @XmlElement(required = true)
    protected String periodId;
    @XmlElement(required = true)
    protected BigDecimal lmee;
    @XmlElement(required = true)
    protected BigDecimal lmef;
    @XmlElement(required = true)
    protected BigDecimal nmea;
    @XmlElement(required = true)
    protected String settId;
    @XmlElement(required = true)
    protected BigDecimal ipGstGmee;
    @XmlElement(required = true)
    protected String version;
    protected boolean nmeaRequired;

    /**
     * Gets the value of the adjustments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentT }
     * 
     * 
     */
    public List<AdjustmentT> getAdjustments() {
        if (adjustments == null) {
            adjustments = new ArrayList<AdjustmentT>();
        }
        return this.adjustments;
    }

    /**
     * Gets the value of the opGstGmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstGmef() {
        return opGstGmef;
    }

    /**
     * Sets the value of the opGstGmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstGmef(BigDecimal value) {
        this.opGstGmef = value;
    }

    /**
     * Gets the value of the opGstLmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstLmee() {
        return opGstLmee;
    }

    /**
     * Sets the value of the opGstLmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstLmee(BigDecimal value) {
        this.opGstLmee = value;
    }

    /**
     * Gets the value of the opGstLmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstLmef() {
        return opGstLmef;
    }

    /**
     * Sets the value of the opGstLmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstLmef(BigDecimal value) {
        this.opGstLmef = value;
    }

    /**
     * Gets the value of the opGstNmea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstNmea() {
        return opGstNmea;
    }

    /**
     * Sets the value of the opGstNmea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstNmea(BigDecimal value) {
        this.opGstNmea = value;
    }

    /**
     * Gets the value of the accountId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * Sets the value of the accountId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountId(String value) {
        this.accountId = value;
    }

    /**
     * Gets the value of the gmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGmee() {
        return gmee;
    }

    /**
     * Sets the value of the gmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGmee(BigDecimal value) {
        this.gmee = value;
    }

    /**
     * Gets the value of the gmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGmef() {
        return gmef;
    }

    /**
     * Sets the value of the gmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGmef(BigDecimal value) {
        this.gmef = value;
    }

    /**
     * Gets the value of the periodId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPeriodId() {
        return periodId;
    }

    /**
     * Sets the value of the periodId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPeriodId(String value) {
        this.periodId = value;
    }

    /**
     * Gets the value of the lmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLmee() {
        return lmee;
    }

    /**
     * Sets the value of the lmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLmee(BigDecimal value) {
        this.lmee = value;
    }

    /**
     * Gets the value of the lmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getLmef() {
        return lmef;
    }

    /**
     * Sets the value of the lmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setLmef(BigDecimal value) {
        this.lmef = value;
    }

    /**
     * Gets the value of the nmea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNmea() {
        return nmea;
    }

    /**
     * Sets the value of the nmea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNmea(BigDecimal value) {
        this.nmea = value;
    }

    /**
     * Gets the value of the settId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSettId() {
        return settId;
    }

    /**
     * Sets the value of the settId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSettId(String value) {
        this.settId = value;
    }

    /**
     * Gets the value of the ipGstGmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIpGstGmee() {
        return ipGstGmee;
    }

    /**
     * Sets the value of the ipGstGmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIpGstGmee(BigDecimal value) {
        this.ipGstGmee = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the nmeaRequired property.
     * 
     */
    public boolean isNmeaRequired() {
        return nmeaRequired;
    }

    /**
     * Sets the value of the nmeaRequired property.
     * 
     */
    public void setNmeaRequired(boolean value) {
        this.nmeaRequired = value;
    }

}
