//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.01 at 03:42:28 PM SGT 
//


package com.emc.sett.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RerunT complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RerunT">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="adjustments" type="{http://www.model.sett.emc.com}AdjustmentT" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="opGstIncGmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="opGstIncLmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="opGstIncLmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="opGstIncNmea" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incGmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incGmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incLmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incLmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="incNmea" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gstRate" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="taxable" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="totalIncGmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalIncGmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalIncLmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalIncLmef" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="totalIncNmea" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ipGstIncGmee" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="ipGstIncNmea" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RerunT", propOrder = {
    "adjustments",
    "opGstIncGmef",
    "opGstIncLmee",
    "opGstIncLmef",
    "opGstIncNmea",
    "incGmee",
    "incGmef",
    "incLmee",
    "incLmef",
    "incNmea",
    "name",
    "gstRate",
    "taxable",
    "totalIncGmee",
    "totalIncGmef",
    "totalIncLmee",
    "totalIncLmef",
    "totalIncNmea",
    "ipGstIncGmee",
    "ipGstIncNmea"
})
public class RerunT {

    protected List<AdjustmentT> adjustments;
    @XmlElement(required = true)
    protected BigDecimal opGstIncGmef;
    @XmlElement(required = true)
    protected BigDecimal opGstIncLmee;
    @XmlElement(required = true)
    protected BigDecimal opGstIncLmef;
    @XmlElement(required = true)
    protected BigDecimal opGstIncNmea;
    @XmlElement(required = true)
    protected BigDecimal incGmee;
    @XmlElement(required = true)
    protected BigDecimal incGmef;
    @XmlElement(required = true)
    protected BigDecimal incLmee;
    @XmlElement(required = true)
    protected BigDecimal incLmef;
    @XmlElement(required = true)
    protected BigDecimal incNmea;
    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected BigDecimal gstRate;
    protected boolean taxable;
    @XmlElement(required = true)
    protected BigDecimal totalIncGmee;
    @XmlElement(required = true)
    protected BigDecimal totalIncGmef;
    @XmlElement(required = true)
    protected BigDecimal totalIncLmee;
    @XmlElement(required = true)
    protected BigDecimal totalIncLmef;
    @XmlElement(required = true)
    protected BigDecimal totalIncNmea;
    @XmlElement(required = true)
    protected BigDecimal ipGstIncGmee;
    @XmlElement(required = true)
    protected BigDecimal ipGstIncNmea;

    /**
     * Gets the value of the adjustments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the adjustments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdjustments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AdjustmentT }
     * 
     * 
     */
    public List<AdjustmentT> getAdjustments() {
        if (adjustments == null) {
            adjustments = new ArrayList<AdjustmentT>();
        }
        return this.adjustments;
    }

    /**
     * Gets the value of the opGstIncGmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstIncGmef() {
        return opGstIncGmef;
    }

    /**
     * Sets the value of the opGstIncGmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstIncGmef(BigDecimal value) {
        this.opGstIncGmef = value;
    }

    /**
     * Gets the value of the opGstIncLmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstIncLmee() {
        return opGstIncLmee;
    }

    /**
     * Sets the value of the opGstIncLmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstIncLmee(BigDecimal value) {
        this.opGstIncLmee = value;
    }

    /**
     * Gets the value of the opGstIncLmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstIncLmef() {
        return opGstIncLmef;
    }

    /**
     * Sets the value of the opGstIncLmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstIncLmef(BigDecimal value) {
        this.opGstIncLmef = value;
    }

    /**
     * Gets the value of the opGstIncNmea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOpGstIncNmea() {
        return opGstIncNmea;
    }

    /**
     * Sets the value of the opGstIncNmea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOpGstIncNmea(BigDecimal value) {
        this.opGstIncNmea = value;
    }

    /**
     * Gets the value of the incGmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncGmee() {
        return incGmee;
    }

    /**
     * Sets the value of the incGmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncGmee(BigDecimal value) {
        this.incGmee = value;
    }

    /**
     * Gets the value of the incGmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncGmef() {
        return incGmef;
    }

    /**
     * Sets the value of the incGmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncGmef(BigDecimal value) {
        this.incGmef = value;
    }

    /**
     * Gets the value of the incLmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncLmee() {
        return incLmee;
    }

    /**
     * Sets the value of the incLmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncLmee(BigDecimal value) {
        this.incLmee = value;
    }

    /**
     * Gets the value of the incLmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncLmef() {
        return incLmef;
    }

    /**
     * Sets the value of the incLmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncLmef(BigDecimal value) {
        this.incLmef = value;
    }

    /**
     * Gets the value of the incNmea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIncNmea() {
        return incNmea;
    }

    /**
     * Sets the value of the incNmea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIncNmea(BigDecimal value) {
        this.incNmea = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the gstRate property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGstRate() {
        return gstRate;
    }

    /**
     * Sets the value of the gstRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGstRate(BigDecimal value) {
        this.gstRate = value;
    }

    /**
     * Gets the value of the taxable property.
     * 
     */
    public boolean isTaxable() {
        return taxable;
    }

    /**
     * Sets the value of the taxable property.
     * 
     */
    public void setTaxable(boolean value) {
        this.taxable = value;
    }

    /**
     * Gets the value of the totalIncGmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIncGmee() {
        return totalIncGmee;
    }

    /**
     * Sets the value of the totalIncGmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIncGmee(BigDecimal value) {
        this.totalIncGmee = value;
    }

    /**
     * Gets the value of the totalIncGmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIncGmef() {
        return totalIncGmef;
    }

    /**
     * Sets the value of the totalIncGmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIncGmef(BigDecimal value) {
        this.totalIncGmef = value;
    }

    /**
     * Gets the value of the totalIncLmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIncLmee() {
        return totalIncLmee;
    }

    /**
     * Sets the value of the totalIncLmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIncLmee(BigDecimal value) {
        this.totalIncLmee = value;
    }

    /**
     * Gets the value of the totalIncLmef property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIncLmef() {
        return totalIncLmef;
    }

    /**
     * Sets the value of the totalIncLmef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIncLmef(BigDecimal value) {
        this.totalIncLmef = value;
    }

    /**
     * Gets the value of the totalIncNmea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalIncNmea() {
        return totalIncNmea;
    }

    /**
     * Sets the value of the totalIncNmea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalIncNmea(BigDecimal value) {
        this.totalIncNmea = value;
    }

    /**
     * Gets the value of the ipGstIncGmee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIpGstIncGmee() {
        return ipGstIncGmee;
    }

    /**
     * Sets the value of the ipGstIncGmee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIpGstIncGmee(BigDecimal value) {
        this.ipGstIncGmee = value;
    }

    /**
     * Gets the value of the ipGstIncNmea property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIpGstIncNmea() {
        return ipGstIncNmea;
    }

    /**
     * Sets the value of the ipGstIncNmea property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIpGstIncNmea(BigDecimal value) {
        this.ipGstIncNmea = value;
    }

}
